// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables. Using fallback values.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://zrutcdhfqahfduxppudv.supabase.co", 
  SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydXRjZGhmcWFoZmR1eHBwdWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjM4MDYsImV4cCI6MjA2MjE5OTgwNn0.QhEjCIkA3KvhVbqkdjFQ6VdJNUI4GdxJ7mrbRm1WIyY"
);